version: "3"

services:
  origin-server:
    build:
      context: ./origin-server
      dockerfile: Dockerfile
    image: re-mlac-origin-server
    restart: always
    ports:
      - "8080:8080"
    environment:
      TZ: "Asia/Seoul"
      ACTIVE_PROFILE: dev
      MYSQL_HOST: mysql-db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: qwer1234
      ANALYSIS_SERVER_HOST: ${ANALYSIS_SERVER_HOST}
      ANALYSIS_SERVER_PORT: ${ANALYSIS_SERVER_PORT}
      VIRTUAL_FIREWALL_HOST: virtual-firewall
      VIRTUAL_FIREWALL_PORT: 8080
      VIRTUAL_WEB_SERVER_HOST: virtual-web-server
      VIRTUAL_WEB_SERVER_PORT: 8080
      VIRTUAL_WEB_APPLICATION_SERVER_HOST: virtual-web-application-server
      VIRTUAL_WEB_APPLICATION_SERVER_PORT: 8080
    networks:
      - mlac
    depends_on:
      - mysql-db
      - virtual-firewall
      - virtual-web-server
      - virtual-web-application-server

  virtual-firewall:
    build:
      context: ./virtual-firewall
      dockerfile: Dockerfile
    image: re-mlac-virtual-firewall
    restart: always
    environment:
      TZ: "Asia/Seoul"
      ACTIVE_PROFILE: dev
      MYSQL_HOST: mysql-db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: qwer1234
    networks:
      - mlac
    ports:
      - "8081:8080"
    depends_on:
      - mysql-db

  virtual-web-server:
    build:
      context: ./virtual-web-server
      dockerfile: Dockerfile
    image: re-mlac-virtual-web-server
    restart: always
    environment:
      TZ: "Asia/Seoul"
      ACTIVE_PROFILE: dev
      MYSQL_HOST: mysql-db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: qwer1234
    networks:
      - mlac
    ports:
      - "8082:8080"
    depends_on:
      - mysql-db
  
  virtual-web-application-server:
    build:
      context: ./virtual-web-application-server
      dockerfile: Dockerfile
    image: re-mlac-virtual-web-application-server
    restart: always
    environment:
      TZ: "Asia/Seoul"
      ACTIVE_PROFILE: dev
      MYSQL_HOST: mysql-db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: qwer1234
    networks:
      - mlac
    ports:
      - "8083:8080"
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0.22
    platform: linux/amd64
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
    ports:
      - "3306:3306"
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mlac

networks:
  mlac:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
